# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca4cb888b9fd5ffc289cd4f5054e51e5dd956f2fe5fa83c6a6bb75306c20f83708ef366796d41d238e41c07739f5216abd557e15408913a864e96b704a22f9a

test:
  secret_key_base: 3302dd1e2019f7913b2ca923227952ed1480f5fa0d672be23fc2630c34027a64e3d303ea80eca9ff16b668239553a053ebfacaacd8e960d2fc5f4f424f3af2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
